---
name: build and publish nornir.tech sources
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publlish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.65.3'
          extended: true
      - name: Build
        run: make gen
      - name: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          cd nornir-automation.github.io
          git add .
          git commit -m "Publishing from $GITHUB_SHA"
          cd ..
          git add nornir-automation.github.io
          git commit -m "updating submodule nornir-automation.github.io"
      - name: Push changes to nornir.tech.src
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Push changes to nornir-automaion.github.io
        uses: ad-m/github-push-action@master
        with:
          directory: nornir-automation.github.io
          branch: master
          force: true
          repository: nornir-automation/nornir-automation.github.io
          github_token: ${{ secrets.PUBLISH_TOKEN }}
