---
name: build nornir.tech sources
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publlish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.65.3'
          extended: true
      - name: Build
        run: make gen
      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
      - name: Publish
        run: make publish
